# Data Science Course Week 1 - Data Manipulation using Pandas

## Here we will be using real data sources to explore the features of Pandas


In [1]:
import pandas as pd

# Class Workshop

## Numpy Overview

* Why Python for Data? Numpy brings *decades* of C math into Python!
* Numpy provides a wrapper for extensive C/C++/Fortran codebases, used for data analysis functionality
* NDAarray allows easy vectorized math and broadcasting (i.e. functions for vector elements of different shapes)

In [6]:
import numpy as np

### Creating ndarrays
An array object represents a multidimensional, homogeneous array of fixed-size items.

In [7]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [8]:
? np.arrange


Object `np.arrange` not found.


In [6]:
a

array([20, 30, 40, 50])

In [8]:
c = a-b
c

array([20, 29, 38, 47])

In [9]:
b**2

array([0, 1, 4, 9])

In [11]:
xxx = np.arange(5,9)
xxx

array([5, 6, 7, 8])

In [11]:
# Creating arrays
a = np.zeros((3))
b = np.ones((2,3))
c = np.random.randint(1,10,(2,3,4))

In [4]:
a

array([ 0.,  0.,  0.])

In [12]:
b

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [13]:
c

array([[[8, 3, 5, 1],
        [5, 8, 1, 2],
        [3, 3, 3, 6]],

       [[7, 5, 5, 8],
        [9, 5, 4, 3],
        [8, 4, 7, 1]]])

## Indexing, Slicing and Iterating

In [14]:
# one-dimensional arrays work like lists:
a = np.arange(10)**2

In [7]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [15]:
a[2:5]

array([ 4,  9, 16])

In [16]:
a[0:3]

array([0, 1, 4])

In [17]:
a[1:3]

array([1, 4])

### Reading Files, Selecting Columns, and Summarizing

MovieLens 100k movie rating data:
    main page: http://grouplens.org/datasets/movielens/
    data dictionary: http://files.grouplens.org/datasets/movielens/ml-100k-README.txt
    files: u.user, u.data, u.item

In [13]:
# can read a file from local computer or directly from a URL
pd.read_table('u.user', header=None)

0
0         1|24|M|technician|85711
1              2|53|F|other|94043
2             3|23|M|writer|32067
3         4|24|M|technician|43537
4              5|33|F|other|15213
5          6|42|M|executive|98101
6      7|57|M|administrator|91344
7      8|36|M|administrator|05201
8            9|29|M|student|01002
9            10|53|M|lawyer|90703
10            11|39|F|other|30329
11            12|28|F|other|06405
12         13|47|M|educator|29206
13        14|45|M|scientist|55106
14         15|49|F|educator|97301
15    16|21|M|entertainment|10309
16       17|30|M|programmer|06355
17            18|35|F|other|37212
18        19|40|M|librarian|02138
19        20|42|F|homemaker|95660
20           21|26|M|writer|30068
21           22|25|M|writer|40206
22           23|30|F|artist|48197
23           24|21|F|artist|94533
24         25|39|M|engineer|55107
25         26|49|M|engineer|21044
26        27|40|F|librarian|30030
27           28|32|M|writer|55369
28       29|41|M|programmer|94043
29           30|7|M|student|55436
..                            ...
913          914|44|F|other|08105
914  915|50|M|entertainment|60614
915       916|27|M|engineer|N2L5N
916        917|22|F|student|20006
917      918|40|M|scientist|70116
918          919|25|M|other|14216
919         920|30|F|artist|90008
920        921|20|F|student|98801
921  922|29|F|administrator|21114
922        923|21|M|student|E2E3R
923          924|29|M|other|11753
924       925|18|F|salesman|49036
925  926|49|M|entertainment|01701
926     927|23|M|programmer|55428
927        928|21|M|student|55408
928      929|44|M|scientist|53711
929      930|28|F|scientist|07310
930       931|60|M|educator|33556
931       932|58|M|educator|06437
932        933|28|M|student|48105
933       934|61|M|engineer|22902
934         935|42|M|doctor|66221
935          936|24|M|other|32789
936       937|48|M|educator|98072
937     938|38|F|technician|55038
938        939|26|F|student|33319
939  940|32|M|administrator|02215
940        941|20|M|student|97229
941      942|48|F|librarian|78209
942        943|22|M|student|77841

[943 rows x 1 columns]

Now having seen the data, read it in again but now with the pipe separator/delimiter.

In [14]:
# read 'u.user' and asign to 'users' so that we can re-use the data
user_cols = ['user_id', 'age', 'gender', 'occupation', 'zip_code']
users = pd.read_table('u.user', sep='|', header=None, names=user_cols, index_col='user_id', dtype={'zip_code':str})

Now try running the example code below, uncommenting each line one at a time to see what results

In [25]:
# examine the users data

#users                   # print the first 30 and last 30 rows
#type(users)             # DataFrame
#users.head()            # print the first 5 rows
#users.head(10)          # print the first 10 rows
#users.tail()            # print the last 5 rows
#users.index             # "the index" (aka "the labels")
#users.columns           # column names (which is "an index")
#users.dtypes            # data types of each column
#users.shape             # number of rows and columns
#users.values            # underlying numpy array
#users.info()            # concise summary (including memory usage)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 943 entries, 1 to 943
Data columns (total 4 columns):
age           943 non-null int64
gender        943 non-null object
occupation    943 non-null object
zip_code      943 non-null object
dtypes: int64(1), object(3)
memory usage: 36.8+ KB


Now try some of the different methods for selecting a column from a dataframe by name.

In [29]:
# select a column

#users['gender']         # select one column
#type(users['gender'])   # Series
#users[['gender']]
#type(users[['gender']])   # DataFrame
#users.gender            # select one column using the DataFrame attribute


pandas.core.frame.DataFrame

Now try some built in pandas methods for producing summary descriptive information from a dataframe.

In [35]:
# summarize (describe) the data

#users.describe()                    # describe all numeric columns
#users.describe(include=['object'])  # describe all object columns (can include multiple types)
#users.describe(include='all')       # describe all columns
#users.gender.describe()             # describe a single column
users.age.mean()                    # only calculate the mean


34.05196182396607

In [37]:
# count the number of occurrences of each value
#users.occupation.value_counts()     # most useful for categorical variables
users.age.value_counts()        # can also be used with numeric variables

30    39
25    38
22    37
28    36
27    35
26    34
24    33
29    32
20    32
32    28
23    28
35    27
21    27
33    26
31    25
19    23
44    23
39    22
40    21
36    21
42    21
51    20
50    20
48    20
49    19
37    19
18    18
34    17
38    17
45    15
      ..
47    14
43    13
46    12
53    12
55    11
41    10
57     9
60     9
52     6
56     6
15     6
13     5
16     5
54     4
63     3
14     3
65     3
70     3
61     3
59     3
58     3
64     2
68     2
69     2
62     2
11     1
10     1
73     1
66     1
7      1
Name: age, dtype: int64

# Student Exercises

## Excercise One

### Data

WHO alcohol consumption data:
    article: http://fivethirtyeight.com/datalab/dear-mona-followup-where-do-people-drink-the-most-beer-wine-and-spirits/    
    original data: https://github.com/fivethirtyeight/data/tree/master/alcohol-consumption
    file: drinks.csv (with additional 'continent' column)


In [38]:
# read drinks.csv into a DataFrame called 'drinks'
drinks = pd.read_table('drinks.csv', sep=',')
drinks = pd.read_csv('drinks.csv')              # assumes separator is comma

In [40]:
# print the head and the tail
drinks.head()
#drinks.tail()

country  beer_servings  spirit_servings  wine_servings  \
0  Afghanistan              0                0              0   
1      Albania             89              132             54   
2      Algeria             25                0             14   
3      Andorra            245              138            312   
4       Angola            217               57             45   

   total_litres_of_pure_alcohol continent  
0                           0.0        AS  
1                           4.9        EU  
2                           0.7        AF  
3                          12.4        EU  
4                           5.9        AF

In [43]:
# examine the default index, data types, and shape
#drinks.index
drinks.dtypes
#drinks.shape

country                          object
beer_servings                     int64
spirit_servings                   int64
wine_servings                     int64
total_litres_of_pure_alcohol    float64
continent                        object
dtype: object

In [45]:
# print the 'beer_servings' Series
#drinks['beer_servings']
drinks.beer_servings


0        0
1       89
2       25
3      245
4      217
5      102
6      193
7       21
8      261
9      279
10      21
11     122
12      42
13       0
14     143
15     142
16     295
17     263
18      34
19      23
20     167
21      76
22     173
23     245
24      31
25     231
26      25
27      88
28      37
29     144
      ... 
163    128
164     90
165    152
166    185
167      5
168      2
169     99
170    106
171      1
172     36
173     36
174    197
175     51
176     51
177     19
178      6
179     45
180    206
181     16
182    219
183     36
184    249
185    115
186     25
187     21
188    333
189    111
190      6
191     32
192     64
Name: beer_servings, dtype: int64

In [49]:
# calculate the average 'beer_servings' for the entire dataset
#drinks.describe()                   # summarize all numeric columns
#drinks.beer_servings.describe()     # summarize only the 'beer_servings' Series
drinks.beer_servings.mean()         # only calculate the mean


106.16062176165804

In [50]:

# count the number of occurrences of each 'continent' value and see if it looks correct
drinks.continent.value_counts()


AF    53
EU    45
AS    44
OC    16
SA    12
Name: continent, dtype: int64

#### Filtering and Sorting

using users data set again

In [55]:
# logical filtering: only show users with age < 20
young_bool = users.age < 20         # create a Series of booleans...
users[young_bool]                   # ...and use that Series to filter rows
users[users.age < 20]               # or, combine into a single step
users[users.age < 20].occupation    # select one column from the filtered results
users[users.age < 20].occupation.value_counts()     # value_counts of resulting Series

student          64
other             4
none              3
entertainment     2
writer            2
artist            1
salesman          1
Name: occupation, dtype: int64

In [58]:
# logical filtering with multiple conditions
users[(users.age < 20) & (users.gender=='M')]       # ampersand for AND condition
users[(users.age < 20) | (users.age > 60)]          # pipe for OR condition
users[users.occupation.isin(['doctor', 'lawyer'])]  # alternative to multiple OR conditions


age gender occupation zip_code
user_id                                
10        53      M     lawyer    90703
125       30      M     lawyer    22202
126       28      F     lawyer    20015
138       46      M     doctor    53211
161       50      M     lawyer    55104
205       47      M     lawyer    06371
251       28      M     doctor    85032
299       29      M     doctor    63108
339       35      M     lawyer    37901
365       29      M     lawyer    20009
419       37      M     lawyer    43215
427       51      M     doctor    85258
444       51      F     lawyer    53202
589       21      M     lawyer    90034
680       33      M     lawyer    90405
841       45      M     doctor    47401
845       64      M     doctor    97405
846       27      M     lawyer    47130
935       42      M     doctor    66221

In [62]:
# sorting
users.age.sort_values()                   # sort a column
users.sort_values(by='age')                   # sort a DataFrame by a single column
users.sort_values(by='age', ascending=False)  # use descending order instead
users.sort_values(by=['occupation', 'age'])   # sort by multiple columns


age gender     occupation zip_code
user_id                                    
118       21      M  administrator    90210
180       22      F  administrator    60202
282       22      M  administrator    20057
317       22      M  administrator    13210
439       23      F  administrator    20817
509       23      M  administrator    10011
394       25      M  administrator    96819
665       25      M  administrator    55412
726       25      F  administrator    80538
78        26      M  administrator    61801
86        26      M  administrator    46005
62        27      F  administrator    97214
525       27      F  administrator    19711
261       28      M  administrator    85202
500       28      M  administrator    94305
748       28      M  administrator    94720
750       28      M  administrator    32303
768       29      M  administrator    12866
922       29      F  administrator    21114
42        30      M  administrator    17870
174       30      F  administrator    52302
190       30      M  administrator    95938
436       30      F  administrator    17345
447       30      M  administrator    55113
95        31      M  administrator    10707
578       31      M  administrator    M7A1A
762       32      M  administrator    95050
940       32      M  administrator    02215
191       33      M  administrator    95161
400       33      F  administrator    78213
...      ...    ...            ...      ...
668       29      F         writer    10016
199       30      M         writer    17604
557       30      F         writer    11217
28        32      M         writer    55369
122       32      F         writer    22206
796       32      F         writer    33755
833       34      M         writer    90019
264       36      F         writer    90064
385       36      M         writer    10003
911       37      F         writer    53210
504       40      F         writer    92115
798       40      F         writer    64131
842       40      M         writer    93055
390       42      F         writer    85016
745       42      M         writer    55113
491       43      F         writer    53711
236       44      F         writer    53214
389       44      F         writer    83702
736       48      F         writer    94618
829       48      M         writer    80209
196       49      M         writer    55105
518       49      F         writer    99709
853       49      M         writer    40515
503       50      F         writer    27514
772       50      M         writer    27105
548       51      M         writer    95468
370       52      M         writer    08534
392       52      M         writer    59801
558       56      F         writer    63132
464       60      M         writer    94583

[943 rows x 4 columns]

## Excercise Two

using the drinks dataset again and refering to the code demonstrated above, write code to answer these questions:

In [68]:
# filter DataFrame to only include European countries
drinks.continent=='EU'

0      False
1       True
2      False
3       True
4      False
5      False
6      False
7       True
8      False
9       True
10      True
11     False
12     False
13     False
14     False
15      True
16      True
17     False
18     False
19     False
20     False
21      True
22     False
23     False
24     False
25      True
26     False
27     False
28     False
29     False
       ...  
163    False
164    False
165     True
166     True
167    False
168    False
169    False
170     True
171    False
172    False
173    False
174    False
175    False
176    False
177    False
178    False
179    False
180     True
181    False
182     True
183    False
184    False
185    False
186    False
187    False
188    False
189    False
190    False
191    False
192    False
Name: continent, dtype: bool

In [70]:
# filter DataFrame to only include European countries with wine_servings > 300
(drinks.continent=='EU') & (drinks.wine_servings > 300)

0      False
1      False
2      False
3       True
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...  
163    False
164    False
165    False
166    False
167    False
168    False
169    False
170    False
171    False
172    False
173    False
174    False
175    False
176    False
177    False
178    False
179    False
180    False
181    False
182    False
183    False
184    False
185    False
186    False
187    False
188    False
189    False
190    False
191    False
192    False
dtype: bool

In [103]:
# calculate the average 'beer_servings' for all of Europe
#drinkseu = drinks.beer_servings(drinks.continent=='EU')
drinks[drinks.continent=='EU'].beer_servings.mean()
#users[users.age < 20].occupation.value_counts()  
#(drinks.continent=='EU')

193.77777777777777

In [88]:
# determine which 10 countries have the highest total_litres_of_pure_alcohol
#users.sort_values(by='age') 
hightest = drinks.sort_values(by='total_litres_of_pure_alcohol')
hightest.tail(10)

country  beer_servings  spirit_servings  wine_servings  \
99           Luxembourg            236              133            271   
155            Slovakia            196              293            116   
81              Ireland            313              118            165   
141  Russian Federation            247              326             73   
61               France            127              151            370   
45       Czech Republic            361              170            134   
68              Grenada            199              438             28   
3               Andorra            245              138            312   
98            Lithuania            343              244             56   
15              Belarus            142              373             42   

     total_litres_of_pure_alcohol continent  
99                           11.4        EU  
155                          11.4        EU  
81                           11.4        EU  
141                          11.5        AS  
61                           11.8        EU  
45                           11.8        EU  
68                           11.9       NaN  
3                            12.4        EU  
98                           12.9        EU  
15                           14.4        EU

# Optional Excercises

### Merging Data

In [93]:
# read 'u.item' into 'movies'
movie_cols = ['movie_id', 'title']
movies = pd.read_table('u.item', sep='|', header=None, names=movie_cols, usecols=[0, 1])


In [94]:
# read 'u.data' into 'ratings'
rating_cols = ['user_id', 'movie_id', 'rating', 'timestamp']
ratings = pd.read_table('u.data', sep='\t', header=None, names=rating_cols)

In [98]:
# merge 'movies' and 'ratings' (inner join on 'movie_id')
movie_ratings = pd.merge(movies, ratings)
movies.shape
ratings.shape
movie_ratings.shape

(100000, 5)

### Grouping Data

In [99]:
movie_ratings.columns

Index(['movie_id', 'title', 'user_id', 'rating', 'timestamp'], dtype='object')

In [100]:
movie_ratings[['title', 'rating']].groupby('title').sum()

rating
title                                                     
'Til There Was You (1997)                               21
1-900 (1994)                                            13
101 Dalmatians (1996)                                  317
12 Angry Men (1957)                                    543
187 (1997)                                             124
2 Days in the Valley (1996)                            300
20,000 Leagues Under the Sea (1954)                    252
2001: A Space Odyssey (1968)                          1028
3 Ninjas: High Noon At Mega Mountain (1998)              5
39 Steps, The (1935)                                   239
8 1/2 (1963)                                           145
8 Heads in a Duffel Bag (1997)                          13
8 Seconds (1994)                                        15
A Chef in Love (1996)                                   33
Above the Rim (1994)                                    15
Absolute Power (1997)                                  428
Abyss, The (1989)                                      542
Ace Ventura: Pet Detective (1994)                      314
Ace Ventura: When Nature Calls (1995)                   99
Across the Sea of Time (1995)                           11
Addams Family Values (1993)                            245
Addicted to Love (1997)                                171
Addiction, The (1995)                                   24
Adventures of Pinocchio, The (1996)                    119
Adventures of Priscilla, Queen of the Desert, T...     399
Adventures of Robin Hood, The (1938)                   254
Affair to Remember, An (1957)                          109
African Queen, The (1951)                              636
Afterglow (1997)                                        56
Age of Innocence, The (1993)                           220
...                                                    ...
Window to Paris (1994)                                   4
Wings of Courage (1995)                                  4
Wings of Desire (1987)                                 228
Wings of the Dove, The (1997)                          276
Winnie the Pooh and the Blustery Day (1968)            285
Winter Guest, The (1997)                                31
Wishmaster (1997)                                       66
With Honors (1994)                                     141
Withnail and I (1987)                                   42
Witness (1985)                                           4
Wizard of Oz, The (1939)                              1003
Wolf (1994)                                            181
Woman in Question, The (1950)                            1
Women, The (1939)                                       55
Wonderful, Horrible Life of Leni Riefenstahl, T...      40
Wonderland (1997)                                       32
Wooden Man's Bride, The (Wu Kui) (1994)                  8
World of Apu, The (Apur Sansar) (1959)                  24
Wrong Trousers, The (1993)                             527
Wyatt Earp (1994)                                      155
Yankee Zulu (1994)                                       1
Year of the Horse (1997)                                23
You So Crazy (1994)                                      3
Young Frankenstein (1974)                              789
Young Guns (1988)                                      324
Young Guns II (1990)                                   122
Young Poisoner's Handbook, The (1995)                  137
Zeus and Roxanne (1997)                                 13
unknown                                                 31
Á köldum klaka (Cold Fever) (1994)                       3

[1664 rows x 1 columns]

### Handling Missing Values

In [102]:
# missing values are usually excluded by default
drinks.continent.value_counts()              # excludes missing values
#drinks.continent.value_counts(dropna=False)  # includes missing values

AF    53
EU    45
AS    44
OC    16
SA    12
Name: continent, dtype: int64

In [ ]:
# find missing values in a Series
drinks.continent.isnull()           # True if missing, False if not missing
drinks.continent.isnull().sum()     # count the missing values
drinks.continent.notnull()          # True if not missing, False if missing
drinks[drinks.continent.notnull()]  # only show rows where continent is not missing

In [ ]:
# use 'tilde' ~ to negate the boolean values
~drinks.continent.isnull()  

In [ ]:
# side note: understanding axes
drinks.sum(axis=0)      # sums "down" the 0 axis (rows)
drinks.sum()            # axis=0 is the default
drinks.sum(axis=1)      # sums "across" the 1 axis (columns)

In [ ]:
# find missing values in a DataFrame
drinks.isnull()             # DataFrame of booleans
drinks.isnull().sum()       # count the missing values in each column

In [ ]:
# fill in missing values
drinks.continent.fillna(value='NA')                 # fill in missing values with 'NA'
drinks.continent.fillna(value='NA', inplace=True)   # modifies 'drinks' in-place